'use strict';
const assert=require('node:assert/strict');
const {Model,fieldDiff}=require('../graph.js');
const nodes=['a','b','c','d','z','old'].map((id,i)=>({id,label:id,current:id!=='old',roles:id==='a'?['primary']:[],x:i*320,y:100,raw:{logical_id:id}}));
const edge=(id,from,to)=>({id,from,to,current:true,category:'science',label:'依赖',path:'M 0 100 C 0 -500 500 -500 500 100',labelX:250,labelY:-300});
const graph={nodes,edges:[edge('ab','a','b'),edge('bc','b','c'),edge('cd','c','d'),edge('da','d','a')],revisionEdges:[{id:'rev',from:'old',to:'a',category:'revision'}],width:2100,height:800};
const m=new Model(graph), ids=()=>m.view().nodes.map(n=>n.id).sort();
m.select('a');m.setFilter('mainline');
assert.deepEqual(ids(),['a','b','d'],'role seeds keep one-hop connectors, not arbitrary transitive closure');
assert.equal(m.view().focusedNodes,1);assert.equal(m.view().contextNodes,2);assert.equal(m.selected,'a');
assert.deepEqual(m.view().edges.map(e=>e.id),['ab','da']);
m.setFilter('alternative');assert.deepEqual(ids(),[]);assert.match(m.notice,/没有.*角色/);
m.back();assert.equal(m.mode,'mainline');m.focus();assert.deepEqual(ids(),['a','b','d']);
m.expand('out');assert.deepEqual(ids(),['a','b','c','d']);
const size=m.stack.length;m.expand('out');assert.equal(m.stack.length,size,'cycle expansion no duplicate frame');
m.pan(22,33);m.zoom(1.4);m.detail={scroll:127,open:['source:one'],focus:'source:one'};
const snapshot=m.snapshot();m.reveal('old');assert.equal(m.selected,'old');assert.equal(m.history,true);assert.equal(m.mode,'mainline','reveal does not silently clear role mode');assert.ok(ids().includes('old'));assert.ok(!ids().includes('z'));
m.back();assert.deepEqual(m.snapshot(),snapshot,'Back restores actual live viewport, local/revealed/detail state');
m.restoreAll();assert.equal(m.selected,'a');assert.equal(m.local,null);assert.ok(ids().includes('z'));
const beforeReset=m.snapshot();m.reset();m.back();assert.deepEqual(m.snapshot(),beforeReset,'reset is a reversible substantive transition');
let stack=m.stack.length;m.pan(1,2);m.zoom(1.1);assert.equal(m.stack.length,stack,'pan/wheel do not push');
m.reveal('a');assert.ok(m.box.w<graph.width/2,'locate uses readable target bounds, not global fit');
m.reveal('ab');assert.ok(m.box.y>-500 && m.box.y+m.box.h>=214,'edge target includes current route and endpoints, not obsolete static curve hull');
const current=m.view().edges.find(e=>e.id==='ab');
const xy=current.path.match(/-?\d+(?:\.\d+)?/g).map(Number);
for(let i=0;i<xy.length;i+=2)assert.ok(xy[i]>=m.box.x&&xy[i]<=m.box.x+m.box.w&&xy[i+1]>=m.box.y&&xy[i+1]<=m.box.y+m.box.h);
for(let i=0;i<65;i++)m.select(i%2?'a':'b');assert.equal(m.stack.length,50);
while(m.back());assert.equal(m.back(),false);assert.equal(m.stack.length,0);
const directional=new Model(graph);directional.select('b');directional.expand('in');assert.deepEqual(directional.local.sort(),['a','b']);directional.expand('in');assert.deepEqual(directional.local.sort(),['a','b','d']);directional.expand('in');assert.deepEqual(directional.local.sort(),['a','b','c','d']);
assert.throws(()=>new Model({...graph,nodes:Array(101).fill(nodes[0])}),/100/);
assert.throws(()=>new Model({...graph,edges:Array(301).fill(graph.edges[0])}),/300/);
assert.equal(typeof fieldDiff,'function');
const diff=fieldDiff({statement:'old text',next_action:{completion_criteria:['old criterion']}},{statement:'new text',next_action:{completion_criteria:['new criterion']}});
assert.ok(diff.rows.some(r=>r.label.includes('陈述')&&r.before==='old text'&&r.after==='new text'));
assert.ok(diff.rows.some(r=>r.label.includes('完成标准')&&r.before.includes('old criterion')&&r.after.includes('new criterion')));
assert.ok(fieldDiff({statement:'x'.repeat(50000)},{statement:'y'.repeat(50000)}).rows.every(r=>r.before.length<=4100&&r.after.length<=4100));
const nested=new Model(graph);nested.select('a');nested.focus();nested.reveal('old');nested.expand('out');assert.ok(nested.view().nodes.some(n=>n.id==='old'),'expansion retains revealed selected node');
const nestedDepth=nested.stack.length;nested.expand('out');assert.equal(nested.stack.length,nestedDepth,'visited/no-new expansion keeps stack');
const unchanged=JSON.stringify(graph);nested.reset();nested.fit();assert.equal(JSON.stringify(graph),unchanged,'immutable graph');
console.log('exploration state, directional cycles, exact Back, bounds and structured diff passed');
